name: CMake

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Workspace for Win32
      run: cmake -E make_directory ${{github.workspace}}/build.win32

    - name: Configure CMake for Win32
      shell: bash
      working-directory: ${{github.workspace}}/build.win32
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_SHELLCODE_GEN=TRUE -DCMAKE_BUILD_TYPE=Release -DBUILD_MMLOADER_DEMO=FALSE
      
    - name: Build for Win32
      working-directory: ${{github.workspace}}/build.win32
      shell: bash
      run: cmake --build --target=Release .

    - name: Create Build Workspace for x64
      run: cmake -E make_directory ${{github.workspace}}/build.x64
      
    - name: Configure CMake for x64
      shell: bash
      working-directory: ${{github.workspace}}/build.x64
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHELLCODE_GEN=TRUE -DBUILD_MMLOADER_DEMO=FALSE
      
    - name: Build for Win64
      working-directory: ${{github.workspace}}/build.x64
      shell: bash
      run: cmake --build --target=Release .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: output
          path: ${{github.workspace}}/output
          
